const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94743595243"
const SESSION_ID = "PRABATH-MD~c1QRCaSS#MjAg7LWinVsBxBZYyabKkFzrE2Y75mqrpaQL34aCHVU"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
